In [3]:
import numpy as np 
 

In [4]:
L = np.array([1,2,3,4])

In [5]:
print(L)

[1 2 3 4]


In [13]:
M = np.matrix('1 2 3; 4 5 6; 6 7 8')

In [14]:
print(M)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [15]:
np.array([1,2,3])

array([1, 2, 3])

In [16]:
z = np.zeros(10)

In [17]:
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [19]:
z = np.zeros((10,10))

In [20]:
z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [21]:
z = np.ones((10,10))

In [22]:
z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [23]:
z = np.random.random((10,10))

In [24]:
z

array([[ 0.43193654,  0.09654345,  0.40288522,  0.70221485,  0.13687687,
         0.76292644,  0.32261408,  0.79281818,  0.99222215,  0.83526209],
       [ 0.83887533,  0.34106855,  0.15952125,  0.50730793,  0.63900277,
         0.67482561,  0.1047059 ,  0.10026291,  0.90619889,  0.32861501],
       [ 0.40180996,  0.65867656,  0.32256214,  0.10925683,  0.88414522,
         0.40429648,  0.39964355,  0.49941747,  0.05518276,  0.31491592],
       [ 0.31290247,  0.15224456,  0.59819141,  0.8801747 ,  0.62003533,
         0.43047284,  0.65121409,  0.72221285,  0.64950039,  0.58059218],
       [ 0.74913191,  0.38649712,  0.98660242,  0.88493059,  0.6641129 ,
         0.96019297,  0.11802575,  0.91387933,  0.89611852,  0.53036495],
       [ 0.55876793,  0.96879127,  0.9409281 ,  0.73584061,  0.45994778,
         0.11395658,  0.99972598,  0.89443479,  0.81360371,  0.93273014],
       [ 0.5443395 ,  0.6143045 ,  0.69845878,  0.52911959,  0.37185217,
         0.238579  ,  0.67792583,  0.01780681